In [1]:
my_list =[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2) #step size

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.linspace(0,5,20) #linspace = number of points you want

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [19]:
#identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#arrays of random numbers

In [23]:
np.random.rand(5)

array([0.05559898, 0.28904926, 0.94101517, 0.58665982, 0.09111723])

In [24]:
np.random.rand(5,5)

array([[0.8544983 , 0.72848227, 0.88963478, 0.29059989, 0.49842634],
       [0.59110098, 0.51534402, 0.40667266, 0.90891825, 0.58781917],
       [0.25422148, 0.26397712, 0.73877045, 0.95686134, 0.8069396 ],
       [0.47851482, 0.51236163, 0.54471786, 0.33439854, 0.7163103 ],
       [0.11659146, 0.45383016, 0.74063119, 0.05479528, 0.65955248]])

In [25]:
#sample from a standard normal distribution or a gaussian

In [28]:
np.random.randn(4)

array([-1.16431481,  0.45138607, -0.7622565 , -0.48735991])

In [30]:
np.random.randn(4,4)

array([[-9.76903050e-02,  2.85918610e+00, -1.50163203e+00,
         3.24973709e-01],
       [ 2.70850407e+00, -1.91961496e-01, -7.89252256e-01,
         8.61464695e-01],
       [-3.92550253e-01,  2.02015244e-02,  1.03428032e+00,
         1.21245206e+00],
       [ 1.40280990e-03,  1.59971224e+00,  2.15012154e+00,
        -1.76014449e-01]])

In [32]:
np.random.randint(1,100,20)

array([13, 63, 62, 94, 58, 92, 91, 36, 61, 46, 26, 44, 24, 36,  2, 20, 58,
       33, 89, 61])

In [33]:
#useful attributes and methods of array 

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr = np.random.randint(0,50,10)

In [38]:
print(ranarr)

[17  6  1 47 24 48 18  3 25 38]


In [39]:
ranarr

array([17,  6,  1, 47, 24, 48, 18,  3, 25, 38])

#### reshape method - return an array containing the same data in new shape

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr.max()

48

In [51]:
ranarr.min()

1

In [52]:
#shape of  a vector

In [53]:
arr.shape

(25,)

In [55]:
arr.dtype

dtype('int32')

In [56]:
from numpy.random import randint

In [57]:
randint(2,20)

7

### numpy indexing and selection

In [59]:
arr = np.arange(0,10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[2]

2

In [63]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [64]:
arr[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])